[package]
name = "riff"
version = "0.2.0"
edition = "2024"
description = "A terminal-first music player where playlists are code."
license = "MIT"
repository = "https://github.com/Nicolas25vlad/riff"
homepage = "https://github.com/Nicolas25vlad/riff"
readme = "README.md"
keywords = ["music", "spotify", "terminal", "tui", "rust"]
categories = ["command-line-utilities", "multimedia::audio"]

[dependencies]
librespot = { version = "0.8.0", default-features = false, features = ["rodio-backend", "rustls-tls-native-roots"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
