from pathlib import Path

path = Path("src/workbench/mod.rs")
text = path.read_text()
old = '''fn draw_playlist(frame: &mut Frame<'_>, area: Rect, workbench: &Workbench) {
    let theme = workbench.state.theme;
    let current = workbench.state.current_index();
    let items = workbench
        .state
        .queue
        .iter()
        .enumerate()
        .map(|(index, item)| {
            let prefix = if Some(index) == current { "▶" } else { " " };
            let text = format!(
                "{prefix} {:>2}. {}\\n      {} · {}",
                index + 1,
                item.title,
                item.artist,
                item.album
            );
            let style = if Some(index) == current {
                Style::default()
                    .fg(theme.accent)
                    .add_modifier(Modifier::BOLD)
            } else {
                Style::default()
            };
            ListItem::new(text).style(style)
        })
        .collect::<Vec<_>>();
    frame.render_widget(
        List::new(items).block(
            Block::default()
                .borders(Borders::ALL)
                .border_style(Style::default().fg(theme.border))
                .title(format!(
                    " {} · {} tracks · generated by code or TUI ",
                    workbench.state.playlist_name,
                    workbench.state.queue.len()
                )),
        ),
        area,
    );
}
'''
new = '''fn playlist_window(total: usize, current: Option<usize>, visible: usize) -> (usize, usize) {
    if total == 0 || visible == 0 {
        return (0, 0);
    }

    let visible = visible.min(total);
    let focus = current.unwrap_or(0).min(total - 1);
    let mut start = focus.saturating_sub(visible / 2);
    if start + visible > total {
        start = total - visible;
    }
    (start, start + visible)
}

fn draw_playlist(frame: &mut Frame<'_>, area: Rect, workbench: &Workbench) {
    let theme = workbench.state.theme;
    let current = workbench.state.current_index();
    let visible_items = usize::from(area.height.saturating_sub(2) / 2).max(1);
    let (start, end) = playlist_window(workbench.state.queue.len(), current, visible_items);
    let items = workbench
        .state
        .queue
        .iter()
        .enumerate()
        .skip(start)
        .take(end.saturating_sub(start))
        .map(|(index, item)| {
            let prefix = if Some(index) == current { "▶" } else { " " };
            let text = format!(
                "{prefix} {:>2}. {}\\n      {} · {}",
                index + 1,
                item.title,
                item.artist,
                item.album
            );
            let style = if Some(index) == current {
                Style::default()
                    .fg(theme.accent)
                    .add_modifier(Modifier::BOLD)
            } else {
                Style::default()
            };
            ListItem::new(text).style(style)
        })
        .collect::<Vec<_>>();
    let window = if start > 0 || end < workbench.state.queue.len() {
        format!(" · showing {}-{}", start + 1, end)
    } else {
        String::new()
    };
    frame.render_widget(
        List::new(items).block(
            Block::default()
                .borders(Borders::ALL)
                .border_style(Style::default().fg(theme.border))
                .title(format!(
                    " {} · {} tracks{} · generated by code or TUI ",
                    workbench.state.playlist_name,
                    workbench.state.queue.len(),
                    window
                )),
        ),
        area,
    );
}
'''
assert old in text, "draw_playlist anchor not found"
text = text.replace(old, new, 1)

test_anchor = '''    #[test]
    fn volume_quantization_uses_five_percent_steps() {
        assert_eq!(quantize_volume_percent(0), 0);
        assert_eq!(quantize_volume_percent(2), 0);
        assert_eq!(quantize_volume_percent(3), 5);
        assert_eq!(quantize_volume_percent(72), 70);
        assert_eq!(quantize_volume_percent(73), 75);
        assert_eq!(quantize_volume_percent(99), 100);
        assert_eq!(quantize_volume_percent(100), 100);
    }
}
'''
test_replacement = '''    #[test]
    fn volume_quantization_uses_five_percent_steps() {
        assert_eq!(quantize_volume_percent(0), 0);
        assert_eq!(quantize_volume_percent(2), 0);
        assert_eq!(quantize_volume_percent(3), 5);
        assert_eq!(quantize_volume_percent(72), 70);
        assert_eq!(quantize_volume_percent(73), 75);
        assert_eq!(quantize_volume_percent(99), 100);
        assert_eq!(quantize_volume_percent(100), 100);
    }

    #[test]
    fn playlist_window_shows_all_short_queues() {
        assert_eq!(playlist_window(3, Some(2), 8), (0, 3));
    }

    #[test]
    fn playlist_window_clamps_near_start() {
        assert_eq!(playlist_window(20, Some(1), 5), (0, 5));
    }

    #[test]
    fn playlist_window_centers_middle_track() {
        assert_eq!(playlist_window(20, Some(10), 5), (8, 13));
    }

    #[test]
    fn playlist_window_clamps_near_end() {
        assert_eq!(playlist_window(20, Some(19), 5), (15, 20));
    }

    #[test]
    fn playlist_window_handles_empty_or_zero_height() {
        assert_eq!(playlist_window(0, None, 5), (0, 0));
        assert_eq!(playlist_window(20, Some(10), 0), (0, 0));
    }
}
'''
assert test_anchor in text, "tests footer anchor not found"
path.write_text(text.replace(test_anchor, test_replacement, 1))
